name: 2my.sk
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "hard_wrap"]

email: tsk at antares
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://2my.sk"
twitter_username: tommy.skodje
github_username:  2my

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "posts"
      lang: "no"
      author:
        name: "Tommy Skodje"
        url: "http://2my.sk"
        profile: "http://www.blogger.com/profile/16604372255669213767?rel=author"
        image: "http://static.flickr.com/93/279356255_fb52db20a0_o.jpg"
      author_image: "http://static.flickr.com/93/279356255_fb52db20a0_o.jpg"
